
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const Administration = lazy(() => import("./pages/Administration.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const MonthlyDetails = lazy(() => import("./pages/MonthlyDetails.tsx"));
const Overview = lazy(() => import("./pages/Overview.tsx"));
const Signup = lazy(() => import("./pages/Signup.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/administration", element: <Administration />},
	{ path: "/", element: <App />},
	{ path: "/login", element: <Login />},
	{ path: "/monthly-details", element: <MonthlyDetails />},
	{ path: "/monthlydetails", element: <MonthlyDetails />},
	{ path: "/overview", element: <Overview />},
	{ path: "/signup", element: <Signup />},

];
